-- Drop the one_liner_hint column from briefs.
-- The one-liner is generated by the blueprint pipeline from the premise;
-- a dedicated brief-level hint is no longer needed.

alter table briefs drop column if exists one_liner_hint;
